spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true

#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000  #默认1000/毫秒
  ReadTimeout: 1000   #默认1000/毫秒
  MaxAutoRetriesNextServer: 1 #默认1
  MaxAutoRetries: 1 #默认0
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management:
  endpoints:
    web:
      exposure:
        include:  hystrix.stream          
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
